# Generated by Django 3.0.2 on 2020-04-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
